### ISSUE TITLE
Verification Constraint AASc-3a-010

### ISSUE THREAD

**Issue by chborntraeger** [aas-core-works/aas-core3.0-typescript#12]
A validation error (AASc-3a-010) is raised when value and value list in data specifications are empty. My understanding is that it is not required to set either value. The constraint only prohibits setting both values, or am I wrong?

**Comment by mristin** [comment]
@chborntraeger here is how we formalized the constraint AASc-3a-010:

https://github.com/aas-core-works/aas-core-meta/blob/396c850c18ca9a7abc9d512ca13c54a287b3f8c0/aas_core_meta/v3.py#L5542-L5554

The text is indeed ambiguous. Please mind that the code in this repository (aas-core3.0-typescript) has been automatically transpiled from https://github.com/aas-core-works/aas-core-meta (with the exception of a few implementation-specific constraints, see https://github.com/aas-core-works/aas-core-meta/blob/396c850c18ca9a7abc9d512ca13c54a287b3f8c0/aas_core_meta/v3.py and search for `@implementation_specific` decorators).

For incorrect formalizations of the constraints and data structures, it would be best to create an issue at https://github.com/aas-core-works/aas-core-meta. This would increase the visibility of the issue much more.

If you think the constraint *per se* should be improved or corrected, I would suggest you to either post an issue to https://github.com/admin-shell-io/aas-specs, or contact IDTA per email directly (please see the email address in the specs document), or participate directly in the IDTA workgroup related to the meta-model.

I'll close this issue here as it is not TypeScript related. Please feel free to re-open if I'm wrong.
